### ISSUE TITLE
French translation too long

### ISSUE THREAD

**Issue by piscoTech** [piscoTech/Workout#16]
Some strings of the French localization (on the [`french`](https://github.com/piscoTech/Workout/tree/french) branch for now) are too long to fit the width of the string as seen in the screenshots.

![Simulator Screen Shot - iPhone 8 - 2019-12-29 at 09 18 17](https://user-images.githubusercontent.com/20811558/71554598-78f79400-2a21-11ea-81bb-5771f9a540ff.png)
![Simulator Screen Shot - iPhone 8 - 2019-12-29 at 09 14 48](https://user-images.githubusercontent.com/20811558/71554599-7d23b180-2a21-11ea-81c9-eebf846a6a65.png)

For the error in the list (displayed only when Health access has not been granted yet) should be fine just dropping _data_ from the original English (`"WRKT_ERR_LOADING" = "Unable to load workout data";`). For the heart zone settings title maybe we should just use the same title as the 2nd section.

@maxime-killinger can you take a look at it?

**Comment by maxime-killinger** [comment]
@piscoTech sorry for the delay. 

The zone settings translation "Zones cardiaques" is ok.

For the WRKT_ERR_LOADING, replacing "Impossible de charger les données d’entraînement" with "Impossible de charger les données de Santé" ("Unable to load Health data") do the trick.
