### ISSUE TITLE
Aggregate Export in CSV

### ISSUE THREAD

**Issue by markwk** [piscoTech/Workout#2]
Another good enhancement would be a high level export of all exports with a row for each workout that would include start, end, duration and, if logged, distance, hr, pace. 

Great app and will investigate the code a bit more to see if I can contribute here depending on how it was built.

**Comment by piscoTech** [comment]
The latest version already include this based on a request from <span>@</span>johnmdandurand on Twitter but upgrades are in order when #1 will be implemented.

**Comment by markwk** [comment]
Great. Thanks @piscoTech.
