### ISSUE TITLE
Missing from iOS App Store?

### ISSUE THREAD

**Issue by fredbenenson** [piscoTech/Workout#29]
Hi there,

I know this is isn't the ideal place to post this, but the App Store is telling me the app is no longer available [when I visit the link](https://apps.apple.com/sk/app/workout-csv-exporter/id1140433100):

![image](https://user-images.githubusercontent.com/195741/218277148-2fa8b8ad-7434-4e3d-902e-295c41ebdc9d.png)

I love the simplicity and functionality of this app and have been using it for years. Which is also a problem because it means all of the data I've been accumulating in a big spreadsheet is in the exact format (column order, etc.) that this app generates. I can't switch to another app because it'd require re-ordering all of my columns and losing some of the ones generated by this app.

Is there a way to get this back up in the app store or maybe sideload it? 

Thanks,

Fred

**Comment by celo-m** [comment]
Hi! I'm from Brazil and getting the same error. I'would love to download it (:

**Comment by piscoTech** [comment]
Hi
Unfortunately with my current work commitments I can no longer maintain or update the app on the AppStore.
